### ISSUE TITLE
File is blank

### ISSUE THREAD

**Issue by jigardhaduk** [devharshit/way2sms-API-client-for-Codeigniter#3]
Dear,
I get a blank file in this repo.
Please provide me it's code.
Thanks.

**Comment by devharshit** [comment]
Hello Jigar,
I have updated that controller file from my end.
Please check it once and let me know if you have any query using it...
Regards, 
Harshit.
[https://hmshingala.wordpress.com/](https://hmshingala.wordpress.com/)
